blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path("", views.get_main_page, name="main_page"),
    path("<int:pk>/", views.get_detail_blog, name="detail"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Author(models.Model):
    full_name = models.CharField(max_length=100, verbose_name="ФИО автора")
    age = models.PositiveSmallIntegerField(verbose_name="Возраст", null=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название категории")

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название блога")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    author = models.ForeignKey(Author, related_name="fk_author", on_delete=models.CASCADE, verbose_name="Автор")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")


class Image(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название картинки")
    image = models.ImageField(upload_to="blog", verbose_name="Картинка")
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="Блог")

    def __str__(self):
        return self.image.url

blog/views.py
from django.shortcuts import render


# Create your views here.
from blog.models import Blog


def get_main_page(request):
    news = Blog.objects.all()
    return render(request, "blog/main_page.html", locals())

def get_detail_blog(request, pk):
    new = Blog.objects.get(id=pk)
    return render(request, "blog/detail_page.html", locals())

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock title%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

</body>
</html>

templates/blog/detail_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>detail page</title>
{% endblock title %}
{% block content %}
<body>
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{new.title}}</h5>
        <p class="card-text">{{new.description}}</p>
        <p class="card-text"><small class="text-body-secondary">{{new.updated_at}}</small></p>
        <p class="card-text"><small class="text-body-secondary">{{new.created_at}}</small></p>

      </div>
    </div>
  </div>
</div>
 {%for image in new.image_set.all%}
<img src="{{image}}" class="img-fluid rounded-start" alt="...">
{%endfor%}

{% endblock content %}

templates/blog/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{%for new in news%}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{new.image_set.first}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{new.title}}</h5>
        <p class="card-text">{{new.description}}</p>
        <p class="card-text"><small class="text-body-secondary">{{new.updated_at}}</small></p>
        <p class="card-text"><small class="text-body-secondary">{{new.created_at}}</small></p>
      </div>
    </div>
  </div>
</div>
{%endfor%}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

</body>
</html>